-- MySQL Script generated by MySQL Workbench
-- Mon Jul 18 13:57:32 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema sysFut
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema sysFut
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `sysFut` DEFAULT CHARACTER SET utf8 ;
USE `sysFut` ;

-- -----------------------------------------------------
-- Table `sysFut`.`jogador`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sysFut`.`jogador` (
  `idjogador` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(80) NOT NULL,
  `instagram` VARCHAR(45) NULL,
  `apelido` VARCHAR(45) NOT NULL,
  `senha` VARCHAR(255) NOT NULL,
  `status` VARCHAR(1) NOT NULL,
  PRIMARY KEY (`idjogador`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sysFut`.`partida`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sysFut`.`partida` (
  `idpartida` INT NOT NULL AUTO_INCREMENT,
  `dataPartida` DATETIME NOT NULL,
  `gol` INT NULL,
  `assistencia` INT NULL,
  `defesa` INT NULL,
  `fk_idjogador` INT NOT NULL,
  PRIMARY KEY (`idpartida`, `fk_idjogador`),
  INDEX `fk_partida_jogador_idx` (`fk_idjogador` ASC) VISIBLE,
  CONSTRAINT `fk_partida_jogador`
    FOREIGN KEY (`fk_idjogador`)
    REFERENCES `sysFut`.`jogador` (`idjogador`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
